### ISSUE TITLE
questions about contributing data from Argentina

### ISSUE THREAD

**Issue by marcosfede** [grote/osm2gtfs#54]
Hello, I hope you don't mind me asking some questions. if this is not the correct place for this, feel free to close this issue.

I'm working on a personal project (mostly for learning) building an open source progressive web app that'll show you bus routes between two points, since I've found no free alternatives that work well in Argentina. 

What I have so far is a basic frontend interface and a python backend that runs querys on a local postgis db to which I have loaded osm data for my region, here is the [code](https://github.com/quecolectivo/server/blob/fab67c06e0ac2a845ba8f300bc5900189114e23d/quecolectivo/api/views.py#L27).  These seems to kinda work but I'm having some trouble with osm2pgsql splitting bus routes into chunks when the route makes a circle and determining the direction so that I only get the A -> B routes.
what do you think of this approach?

yesterday I saw your youtube video about transportr and I wonder if using gtfs data is strictly necessary in order to search routes (if I don't care about arrival and departure times yet) ?

another question would be if you could provide me some basic info about how I would adapt this library so I can try to get data from Argentina and contribute that to navitia. There are some closed source apps like Moovit and mapa.buenosaires.gob.ar that have departure and arrival times, so I'm trying to figure out how to get them as well. (the latter being a government website, so I send some emails but they have not answered yet)

Thanks in advance

**Comment by grote** [comment]
Hey @marcosfede, thanks for your interest in this project! :)

> if this is not the correct place for this, feel free to close this issue.

Normally, issue tickets are not for questions, but since we don't offer an alternative place that is fine. I am going to close it (since it doesn't track activity necessary for the project), but that doesn't need to stop the discussion.

> I'm having some trouble with osm2pgsql splitting bus routes into chunks when the route makes a circle and determining the direction so that I only get the A -> B routes.
what do you think of this approach?

I am personally not familiar with osm2pgsql, so I don't know if it extracts sufficient information or if the route direction is even available in OSM.

> yesterday I saw your youtube video about transportr and I wonder if using gtfs data is strictly necessary in order to search routes (if I don't care about arrival and departure times yet) ?

GTFS data is never strictly necessary, it is just the de-facto standard that makes working with transport data easier, because there are so many tools to work with it already.

If you just want to display all routes, GTFS is overkill. Maybe https://github.com/xamanu/mapanica-rutas is interesting for you.

> another question would be if you could provide me some basic info about how I would adapt this library

We have a ticket to document this, let me give a short first answer there: #53

> There are some closed source apps like Moovit and mapa.buenosaires.gob.ar that have departure and arrival times, so I'm trying to figure out how to get them as well. (the latter being a government website, so I send some emails but they have not answered yet)

Yes, the best approach is to see first if there is any possibility of retrieving GTFS data, so you don't need create it yourself. Moovit most likely has GTFS data internally that they don't publish. I don't know how they got it whether they created it themselves or whether got it from someone.
