### ISSUE TITLE
Inconsistent usage of a parameter in Route Class

### ISSUE THREAD

**Issue by jamescr** [grote/osm2gtfs#71]
The `stops` parameter of `Route Class` is a list the is being assigned with two different object types during the default execution of the script. 

In `osm_connector` it is a list of strings, where each string corresponds to the node ID of the stop in OSM. In the `default creator` the stop parameter is changed to a list of osm2gtfs `Stop Objects`.

**Comment by xamanu** [comment]
This is related and hs been addressed within the work on the data structure #30 - at least for the [standard stops_creator](https://github.com/mapanica/osm2gtfs/blob/master/osm2gtfs/creators/stops_creator.py). In order to allow backwards compatibility with existing creators, this logic has been moved to the [routes_creator_incofer](https://github.com/mapanica/osm2gtfs/blob/master/osm2gtfs/creators/incofer/routes_creator_incofer.py) and [routes_creator_fenix](https://github.com/mapanica/osm2gtfs/blob/master/osm2gtfs/creators/fenix/routes_creator_fenix.py).

**Comment by xamanu** [comment]
Resolved with accepted PR #99
